name: Elixir CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test / OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['24.2']
        elixir: ['1.13.2']
    steps:
      - uses: actions/checkout@v2

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
          otp-version: ${{ matrix.otp }} # Define the OTP version [required]

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v1
        id: mix-deps-cache #id to use in retrieve action
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-deps-${{ github.event.pull_request.base.sha }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-deps-${{ github.event.pull_request.base.sha }}-
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-deps

      - name: Retrieve Mix Build Cache
        uses: actions/cache@v1
        id: mix-build-cache #id to use in retrieve action
        with:
          path: _build/test/lib
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-build-${{ github.event.pull_request.base.sha }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-build-${{ github.event.pull_request.base.sha }}-
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-build-

      - name: Install Mix Dependencies
        #if: steps.mix-deps-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check Formatting
        run: |
          mix format --check-formatted

      - name: Clean
        run: mix clean

      - name: Compile
        run: mix compile

      - name: Run Credo
        run: mix credo --strict

      - name: Run Tests
        # run: mix test
        run: mix coveralls.github

      - name: Retrieve PLT Cache
        uses: actions/cache@v1
        id: plt-cache
        with:
          path: plts
          key: v4-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ github.event.pull_request.base.sha }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            v4-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ github.event.pull_request.base.sha }}-
            v4-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-

      - name: Run dialyzer
        run: mix dialyzer